#!/bin/sh
# Turns a directory of screens into one C source: every file embedded by the
# compiler (C23 #embed), addressed by its path relative to the tree. The shell
# carries its screens inside the binary, so opening one is a pointer and a
# length, not a request to the host and a state machine waiting for the answer.
#
# The output belongs in build/, one level below the tree, which is what the
# "../" in each #embed is relative to: the directive resolves against the
# directory of the file that holds it, so the build works from any cwd.
# C23 #embed is the fast path, but GCC only got it in 15 and the firmware
# toolchain is 14.2 — so "--bytes" writes plain arrays instead, which no
# compiler has to have a feature for. The output is generated either way.
set -eu
bytes=0
if [ "${1-}" = "--bytes" ]; then
	bytes=1
	shift
fi
[ $# -ge 1 ] || { echo 'usage: embed.sh [--bytes] <dir>...  (output belongs in build/)' >&2; exit 2; }
# several roots make one tree, each file addressed by its path under its own
# root: the screens, and the units compiled from them
tab=$(printf '\t')
list=$(for root in "$@"; do
	(cd "$root" && find . -type f ! -name '.*') | sed "s|^\./|$root$tab|"
done | LC_ALL=C sort -t "$tab" -k 2)

printf '/* generated by tools/embed.sh from %s: do not edit */\n' "$*"
printf '#include "tree.h"\n\n'

i=0
echo "$list" | while IFS="$tab" read -r root f; do
	[ -n "$f" ] || continue
	printf 'static const uint8_t scr_b%d[] = {\n' "$i"
	# the trailing NUL is not the length: a screen is bytes, and the zero is
	# only there so a stray string function cannot walk off the end
	if [ "$bytes" -eq 1 ]; then
		od -An -v -tu1 "$root/$f" | awk '{for (i = 1; i <= NF; i++) printf "%s,", $i; print ""}'
		printf '0\n'
	else
		printf '#embed "../%s/%s" suffix(, 0) if_empty(0)\n' "$root" "$f"
	fi
	printf '};\n'
	i=$((i + 1))
done

printf '\nconst tree_file tree_files[] = {\n'
i=0
echo "$list" | while IFS="$tab" read -r root f; do
	[ -n "$f" ] || continue
	printf '    {"%s", scr_b%d, sizeof scr_b%d - 1},\n' "$f" "$i" "$i"
	i=$((i + 1))
done
printf '};\n\n'

n=$(echo "$list" | grep -c . || true)
printf 'const size_t tree_nfiles = %s;\n' "$n"
